# WinGet configuration file to install Docker Desktop in a silent mode.
$schema: https://aka.ms/winget-packages.schema.2.0.json
CreationDate: '2025-06-25'
WinGetVersion: '1.6.2771'

Packages:
  - PackageIdentifier: Docker.DockerDesktop
    InstallOptions:
      Silent: true
      AcceptPackageAgreements: true
      AcceptSourceAgreements: true

